site_name: co-rc docs
site_url: https://co-rc.github.io/
repo_url: https://github.com/co-rc/co-rc.github.io
repo_name: co-rc/co-rc.github.io

theme:
  name: material
  palette:
    - scheme: default
      primary: cyan
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - material/.icons
  - pymdownx.saneheaders
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: co-rc
      repo: co-rc.github.io
  - pymdownx.smartsymbols
  - pymdownx.mark
  - admonition
  - def_list
  - pymdownx.progressbar

plugins:
  - search
  - awesome-nav

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/co-rc/

copyright: "Â©2025 <a href=\"https://github.com/jbanaszczyk\">jbanaszczyk</a>"

extra_css:
  - stylesheets/extra.css
